project:
  type: website


website:
  title: "Councilytics"
  page-footer: 
    center: |
      [Contact Madison Councilytics](mailto:contact@councilytics.com)
  navbar:
    title: false
    logo: "MC_Logo_Stacked.svg"
    logo-href: index.qmd
    background: "#66cbff"
    left: 
      - text: What Happened at...
        menu:  
         - property-index.qmd
         - Plan_Commission.qmd
         - Landmarks.qmd
         - Urban_Design.qmd
      - text: Voting Record
        menu: 
         - index.qmd
         - Historical_2023_25_Voting.qmd
      - about.qmd
      - text: Who's Your Alder?
        href: https://www.cityofmadison.com/council/councilmembers/findAlderByAddress.cfm
    right:
    - text: "☕ Support Madison Councilytics"
      href: https://www.buymeacoffee.com/councilytics

  search:
   location: navbar
   type: overlay

# contents:
#   - index.qmd

format:
  html:
    embed-resources: true
    theme: cosmo
    html-table-processing: none
    page-layout: full
    css: styles.css

