project:
  type: website


website:
  title: " "
  page-footer: 
    center: |
      [Contact Madison Councilytics](mailto:mail@mjzenz.org)
    right: |
      [Source Code](https://github.com/mjzenz/madison-alder-dashboard)
  navbar:
    logo: "Councilytics_medium_pic.png"
    logo-href: https://councilytics.mjzenz.org
    background: "#66cbff"
    left: 
      - text: Who's Your Alder?
        href: https://www.cityofmadison.com/council/councilmembers/findAlderByAddress.cfm
    #right:
     # - about.qmd
    #  - text: Voting Records
     #   menu:
      #    - Madison_alder_votes.qmd
        #  - Alder_Detail.qmd
    #  - text: Election 2025
     #   menu: 
      #    - Candidate_Summary.qmd
  #search:
   #location: navbar
    #type: overlay

# contents:
#   - index.qmd

format:
  html:
    embed-resources: true
    theme: cosmo
    html-table-processing: none
    page-layout: full
