---
title: "Alder Voting Record"
format: html
editor: visual
---

```{r}
#| label: loaddata
#| echo: false
#| warning: false
#| message: false

library(tidyverse)
library(kableExtra)

load("alder_data_processed.RData")

```

## Percentage Pro-development and housing voting records (YIMBY), 2023-25 term

```{r}
#| label: tab-YIMBY_percentage
#| echo: false
#| warning: false
#| message: false
kableExtra::kable(YIMBY.prop, "html") |>
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))



```

## Development and housing votes

```{r}
#| label: tbl-all-votes
#| tbl-cap: Votes of active alders. YIMBY votes in blue, anti-YIMBY votes in red.
#| echo: false
#| warning: false
#| message: false



    kable(YIMBY.vote.list, "html", escape = FALSE) %>%
  column_spec(5,color = ifelse(((YIMBY.vote.list$YIMBY & YIMBY.vote.list$`1` == "Y") |
                                 (!YIMBY.vote.list$YIMBY & YIMBY.vote.list$`1` == "N"))
                               | is.na(YIMBY.vote.list$`1`)  , "blue", "red")) %>%
  column_spec(6,color = ifelse(((YIMBY.vote.list$YIMBY & YIMBY.vote.list$`2` == "Y") |
                                 (!YIMBY.vote.list$YIMBY & YIMBY.vote.list$`2` == "N"))
                               | is.na(YIMBY.vote.list$`2`)  , "blue", "red")) %>%
  column_spec(7,color = ifelse(((YIMBY.vote.list$YIMBY & YIMBY.vote.list$`3` == "Y") |
                                 (!YIMBY.vote.list$YIMBY & YIMBY.vote.list$`3` == "N"))
                               | is.na(YIMBY.vote.list$`3`)  , "blue", "red")) %>%
 column_spec(8,color = ifelse(((YIMBY.vote.list$YIMBY & YIMBY.vote.list$`4` == "Y") |
                                 (!YIMBY.vote.list$YIMBY & YIMBY.vote.list$`4` == "N"))
                               | is.na(YIMBY.vote.list$`4`)  , "blue", "red")) %>%
  column_spec(9,color = ifelse(((YIMBY.vote.list$YIMBY & YIMBY.vote.list$`5` == "Y") |
                             (!YIMBY.vote.list$YIMBY & YIMBY.vote.list$`5` == "N"))
                           | is.na(YIMBY.vote.list$`5`)  , "blue", "red")) %>%
  column_spec(10,color = ifelse(((YIMBY.vote.list$YIMBY & YIMBY.vote.list$`6` == "Y") |
                                 (!YIMBY.vote.list$YIMBY & YIMBY.vote.list$`6` == "N"))
                               | is.na(YIMBY.vote.list$`6`)  , "blue", "red")) %>%
  column_spec(11,color = ifelse(((YIMBY.vote.list$YIMBY & YIMBY.vote.list$`7` == "Y") |
                                 (!YIMBY.vote.list$YIMBY & YIMBY.vote.list$`7` == "N"))
                               | is.na(YIMBY.vote.list$`7`)  , "blue", "red")) %>%
  column_spec(12,color = ifelse(((YIMBY.vote.list$YIMBY & YIMBY.vote.list$`8` == "Y") |
                                 (!YIMBY.vote.list$YIMBY & YIMBY.vote.list$`8` == "N"))
                               | is.na(YIMBY.vote.list$`8`)  , "blue", "red")) %>%
  column_spec(13,color = ifelse(((YIMBY.vote.list$YIMBY & YIMBY.vote.list$`9` == "Y") |
                                 (!YIMBY.vote.list$YIMBY & YIMBY.vote.list$`9` == "N"))
                               | is.na(YIMBY.vote.list$`9`)  , "blue", "red")) %>%
        column_spec(14,color = ifelse(((YIMBY.vote.list$YIMBY & YIMBY.vote.list$`10` == "Y") |
                                 (!YIMBY.vote.list$YIMBY & YIMBY.vote.list$`10` == "N"))
                               | is.na(YIMBY.vote.list$`10`)  , "blue", "red")) %>%
        column_spec(15,color = ifelse(((YIMBY.vote.list$YIMBY & YIMBY.vote.list$`11` == "Y") |
                                 (!YIMBY.vote.list$YIMBY & YIMBY.vote.list$`11` == "N"))
                               | is.na(YIMBY.vote.list$`11`)  , "blue", "red")) %>%
        column_spec(16,color = ifelse(((YIMBY.vote.list$YIMBY & YIMBY.vote.list$`12` == "Y") |
                                 (!YIMBY.vote.list$YIMBY & YIMBY.vote.list$`12` == "N"))
                               | is.na(YIMBY.vote.list$`12`)  , "blue", "red")) %>%
        column_spec(17,color = ifelse(((YIMBY.vote.list$YIMBY & YIMBY.vote.list$`13` == "Y") |
                                 (!YIMBY.vote.list$YIMBY & YIMBY.vote.list$`13` == "N"))
                               | is.na(YIMBY.vote.list$`13`)  , "blue", "red")) %>%
        column_spec(18,color = ifelse(((YIMBY.vote.list$YIMBY & YIMBY.vote.list$`14` == "Y") |
                                 (!YIMBY.vote.list$YIMBY & YIMBY.vote.list$`14` == "N"))
                               | is.na(YIMBY.vote.list$`14`)  , "blue", "red")) %>%
        column_spec(19,color = ifelse(((YIMBY.vote.list$YIMBY & YIMBY.vote.list$`15` == "Y") |
                                 (!YIMBY.vote.list$YIMBY & YIMBY.vote.list$`15` == "N"))
                               | is.na(YIMBY.vote.list$`15`)  , "blue", "red")) %>%
        column_spec(20,color = ifelse(((YIMBY.vote.list$YIMBY & YIMBY.vote.list$`16` == "Y") |
                                 (!YIMBY.vote.list$YIMBY & YIMBY.vote.list$`16` == "N"))
                               | is.na(YIMBY.vote.list$`16`)  , "blue", "red")) %>%
        column_spec(21,color = ifelse(((YIMBY.vote.list$YIMBY & YIMBY.vote.list$`17` == "Y") |
                                 (!YIMBY.vote.list$YIMBY & YIMBY.vote.list$`17` == "N"))
                               | is.na(YIMBY.vote.list$`17`)  , "blue", "red")) %>%
        column_spec(22,color = ifelse(((YIMBY.vote.list$YIMBY & YIMBY.vote.list$`18` == "Y") |
                                 (!YIMBY.vote.list$YIMBY & YIMBY.vote.list$`18` == "N"))
                               | is.na(YIMBY.vote.list$`18`)  , "blue", "red")) %>%
       column_spec(23,color = ifelse(((YIMBY.vote.list$YIMBY & YIMBY.vote.list$`19` == "Y") |
                                 (!YIMBY.vote.list$YIMBY & YIMBY.vote.list$`19` == "N"))
                               | is.na(YIMBY.vote.list$`19`)  , "blue", "red")) %>%
       column_spec(24,color = ifelse(((YIMBY.vote.list$YIMBY & YIMBY.vote.list$`20` == "Y") |
                                 (!YIMBY.vote.list$YIMBY & YIMBY.vote.list$`20` == "N"))
                               | is.na(YIMBY.vote.list$`20`)  , "blue", "red")) %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))



```
