---
title: "Plan Commission"
format: html
editor: visual
---

## Property Summary

## Meeting Summaries

### 2025-01-13, Tuesday 5:30pm

By Tori Cooper

Also [live-tweeted on Bluesky by ZENZ](https://bsky.app/profile/therealzenz.bsky.social/post/3lfnus6dbkk2f)

[Official Minutes](https://madison.legistar.com/View.ashx?M=M&ID=1235143&GUID=C9FAD12E-E83A-41FE-89D4-18B6F81CB209)

Tuesday night’s Planning Commission Committee Meeting ran almost two and a half hours—primarily focusing on two key items:

1.  Conditional use for the Essen Haus to expand its hours of outside operation.
2.  the proposed demolition of two neighboring homes in the Wingra Neighborhood, with plans to build one single-family residence in their place.

Before diving into the issues, the committee voted to unanimously pass approved consent items such as:

#### Consent Agenda

-   **Rezoning** at **709 Northport Drive** in District 18 from SR-01 to TR-U1 ([Legistar 83924](https://madison.legistar.com/LegislationDetail.aspx?ID=7040532&GUID=AF384506-98B5-4DF3-B123-5A9BF2570F10&Options=ID%7CText%7C&Search=83924)).
-   Allowing **conditional use** at **908 E. Main Street** in District 6 for a beauty school in a multi-use complex ([Legistar 86416](https://madison.legistar.com/LegislationDetail.aspx?ID=7045337&GUID=ECC2B330-EA80-4550-8A81-E2F2913A3AAE&Options=ID%7CText%7C&Search=86416)).
-   Permitting an **accessory building** on a lake-front property at **913 Woodward Drive** in District 18 ([Legistar 86418](https://madison.legistar.com/LegislationDetail.aspx?ID=7045485&GUID=B796A950-A446-4EDB-B061-8ECD7554E0E2&Options=ID%7CText%7C&Search=86418)).
-   Permission to **eliminate a facade (demolition)** on a street-facing, single-family residence located at **2449 Fox Avenue** in District 13 ([Legistar 86420](https://madison.legistar.com/LegislationDetail.aspx?ID=7045487&GUID=0F94D0BC-EE2C-446F-B04F-CA9BF3DEC8C9&Options=ID%7CText%7C&Search=86420)).
-   Approval to obtain a **certified survery map** for a residential lot at **4952 Thorston Road** in Sun Prairie in order to begin plans for two multi-family complexes ([Legistar 86421](https://madison.legistar.com/LegislationDetail.aspx?ID=7045510&GUID=AB0B1694-77D0-4912-9579-482E42FD0BA5&Options=ID%7CText%7C&Search=86421)).

#### Essen Haus, 506-518 E Wilson Street, Conditional Use

[Legistar 86417](https://madison.legistar.com/LegislationDetail.aspx?ID=7045484&GUID=31CD8EDB-C310-4A5B-A556-5975E1EABE2B)

Prior to re-zoning from PD to UMX, Essen Haus operated later into the evening and ran their Volleyball league two hour past the allowed hours stipulated by the current conditional use agreement. The application includes requests for live music events, later volleyball league end times, use of an outdoor eating patio, and later closing time requirements. Essen Haus and Come Back In owner, Robert Worm, spoke to the committee regarding the benefits of expanding events and hours at Essen Haus, arguing later hours made for a more active neighborhood. In his argument, which was echoed by other members or the public, Worm referenced a decline in undesirable behavior. The previous red-light take-over of the area in the ‘70s and ‘80s declined, and “vice type’ behavior prevalent in the ‘90s faded out as the Essen Haus and Come Back In supported a more active nightlife in the area; however, neighbors in the area were not enthusiastic about the proposed changes to the agreement. Bob J. and Stephen O’Neal, two nearby residents, argued against Worm’s appeal, both citing the noise as a primary reason for their concerns. While O’Neal made it clear he is not opposed to the activities themselves, the concern lies in disturbing what has become a residentially-dense neighborhood. Worm blames the disagreement on the change in management and residents in the condo he built in 1985 and later sold. Plan Commission ultimately allowed conditional use for later Volleyball hours in a unanimous vote; however, the approval was contingent on the operating under the similar conditions as the 2024 approval, meaning continuing to end serving at 9pm, limiting live music events to two instead of three, and having doors to the patio area remain closed to prevent excess noise.


#### 1007 Edgewood Ave., Demolition

[Legistar 86419](https://madison.legistar.com/LegislationDetail.aspx?ID=7045486&GUID=1C0AA69E-C841-4C0A-B93D-9D0E688CC257&Options=ID|Text|&Search=86419)

The Committee also addressed reapplication to demolish two single-family homes in the Wingra neighborhood. While the intended use for the lot is to create one, single-family residence, City Staff member Megan Tuttle noted that the intended use could not be considered as part of the proposal. John Collins, who holds the homes under Edgewood Park LLC., was represented at the meeting by Chris Nelson and Robert Procter. Nelson and Proctor argued the home should not be considered historical due to ‘unsympathetic alterations,’ which include the addition of vinyl siding on both homes and vinyl windows at 1007 Edgewood Ave. Several residents, some of which have experience rehabbing historical homes or with their certification, raised the question of the original wood siding being hidden underneath the vinyl. Bonnie Gruber, who shared a similar argument as other speakers in opposition of the demolition, stated a single residence replacing the two goes against Madison’s housing initiatives. Further stating each property should remain “a simple home for ordinary people and Madison cares about ordinary people.” Bob Klebba, expanded on Gruber’s statement, saying the reports submitted to the city supporting demolition read more like realtor’s evaluations—highlighting the applicants’ lack of official reports from the fire department, city, or similar certified entities. Ultimately, the demolition was denied by the committee for a second time, despite the attendance of attorneys representing John Collin’s and Edgewood Park, LLC.

#### 6201 Old Middleton Rd., Certified Survey Map
 
 Legistar 86415](https://madison.legistar.com/LegislationDetail.aspx?ID=7045770&GUID=E7CBF326-10DD-41C0-8100-61BF440A7FFC)
 
After spending over an hour hearing speakers in support and opposition of the demolition application, the committee wrapped up their meeting with a brief review and vote towards approving an official survey map for a parcel located at 6201 Old Middleton Road on Madison’s west side. While questions were raised about the accuracy of an areal survey that had been conducted, City staff Chris Wells confirmed the discrepancy, noting that areal surveys are often only estimates whereas physical surveys yield actual square footage of the area in question. The intended use for the lot(s) in question would include one or multiple deep end residences. The movement for an official survey passed unanimously, and intended use will be determined at a later time, pending the survey’s findings.


### 2025-02-03, Tuesday 5:30pm

By Tori Cooper

Also [live-tweeted on Bluesky by ZENZ](https://bsky.app/profile/therealzenz.bsky.social/post/3lfnus6dbkk2f)

[Official Minutes](https://madison.legistar.com/View.ashx?M=M&ID=1235144&GUID=15A19A7C-6944-4DD4-B5EB-CCDE285764AC)


#### Consent Agenda



#### 

[Legistar 86417](https://madison.legistar.com/LegislationDetail.aspx?ID=7045484&GUID=31CD8EDB-C310-4A5B-A556-5975E1EABE2B)


### 2025-02-17, Tuesday 5:30pm

By Tori Cooper

Also [live-tweeted on Bluesky by ZENZ]()

[Official Minutes](https://madison.legistar.com/View.ashx?M=M&ID=1235145&GUID=933F3815-41C9-4E92-8BA2-6EDF752435C9)

Madison’s Plan Commission met Tuesday, February 17 to discuss several developments items—mainly focusing on amendments to Tax Incremental Districts (TIDs) and accessory dwelling units. The meeting was held virtually, with Alder Field notably starting the meeting out during his evening Madison Metro ride home.

Before diving in to their key items, the Commission differed discussion of conditional use at 3915 Lien Road in District 3, in which a dive through window for a coffee shop is being requested (Legistar 86523). Additionally, the Committee unanimously passed their consent agenda, which included:


#### Consent Agenda

Consideration of a demolition permit for a single family home located at 2530 Dahle Street in District 12 (Legistar 86523)
Consideration of a demolition permit for a two-family residence at 6111 Femrite Drive in District 16 (Legistar 86730)
Consideration of a demolition permit for a single family residence located at 6213 Countryside Lane in District 19 (Legistar 86731)
Approval of preliminary platting of Hill Valley, located in District 1, which includes 940-1050 South High Point Road, 1051 Pleasantview Road, and 902 Landmark Trail (Legistar 86737)
Approval of Hill Valley plat in District 1, located at 1050 South Highpoint Road and 1051 Pleasantview Road (Legistar 86738)





#### Tax Incremental District Amendments 


[Legistar ]()

The Commission then moved on to public hearings related to proposals for changes to TIDs for District 6 and District 12. Amending the TIDs and gaining board approval would allow the City to use overlaying tax districts levie to invest in other parts of the Madison community. Funds could be used for items such as redeveloping property, improvements to streets and lighting, as well as offer assistance to businesses. Typically, items are still in the conception phase; however, public improvements tend to be more planned out and “ready to go,” according to Rolls. Public improvement items in the current proposal include additional lighting along Fish Hatchery Road to increase public safety.

The plan commission is the first step in this process, where they take into consideration recommendations and flight studies showing the proposals are found to have at minimum a 51% improvement without the potential for conflicts of interest. If the Commission passes the proposed amendment, items are then put in front of a board of approval. The board is made up of five voting members, including a representative from the City, County, School Board, Technical College, and a member of the public who is selected by the four core voting members. If passed by the board, the city may proceed with amendments and distribution of funds.

The first TID amendment up for approval was Legistar 86995 for Capitol Gateway in District 6 and District 12. Linda Lindt, a public registrant, questioned the City’s ability to reallocate funds after losing a $4 Million grant, claiming this amendment could no longer be properly funded with its loss. Rolls differed comment, stating that the Parks Division would have more information regarding the loss of the grant; however, Rolls highlighted how previously amended TIDs have helped public entities such as Breese Steven’s field. Notably mentioning how the facility houses a myriad of events which bring in considerable revenue for the City. Rolls further emphasized that the revenue brought to the city would allow for further improvements, so the initial reallocation will have an eventual payout and positive impact on the community.

The Commission then moved on to discuss Legistar 86996, which would amend TID 44 for parts of District 3 and District 15. Although their were no public registrants, Commissioner Solheim asked about the potential impact on small businesses. Rolls confirmed that businesses within a half mile radius of the TID would be eligible for loans.

Next up for discussion was the project plan and boundary for TID 46, which covers Research Park in District 11 and District 19 (Legistar 87015) and TID 51 which covers parts of South Madison in District 14. Although there was not new comment from either public registrants, Commissioner Heck prompted discussion on $5 Million being allocated to affordable housing near the South Transfer Point and taking money away from Madison’s Land Banking. Heck further asked as to the City’s rational behind this specific site. Rolls assured the Commission there was still money set aside for further Land Banking and that the proposed affordable housing would not get in the way of future land bank opportunities. As for rational, Madison’s south side has been identified as an area of need, and aligning need with access to public transportation aligns with the 2025 Comprehensive Plan evaluated in the Commission's last meeting.

#### Demolition Permit Approval Process Updates
Next up on the Commission’s agenda was repealing section 28.185 of Madison’s general ordinance to make way for ordinance 41.28, which would update the approval process for demolition permits (Legistar 86649). City Staff Megan Tuttle presented, sharing how most demolitions that come to the Plan Commission are not historic buildings or homes, the process can often be unclear, and how some building pose an imminent threat to public safety—needing a streamlined process of approval. Since October 2021, the Commission has reviewed 143 demolition applications for almost 250 individual buildings with a 96% percent approval rate. Of those, 70% were found to have no known historic value. Of the 9% of buildings approved for demolition and that were found to have historic value, 18% were considered “regrettable losses.” Ultimately, the update aims to move four core administrative aspects of the process to later points in planning, which will allow the City to process applications more effectively and efficiently.

To no surprise, several members of the Madison Trust for Historic Preservation (MTHP) were present for the public hearing. Rick Chandler, president of MTHP, stated they commend some of the changes, but have concerns over others. Namely, the potential negative impact the changes will have in tipping the scale to favor demolition rather than protecting the city’s heritage. Chandler stated denials of permits had no impact on the housing crisis Madison is currently facing, but that approvals created the potential for fewer middle housing units. This calls back to an earlier meeting in 2025 where a family was appealing a 2024 demolition permit denial to tear down two homes in the Vilas Neighborhood in order to build a larger, single family home that MTHP deemed “a mansion.” Chandler further cited changes to factor IV, where minor mitigation stents such as recycling materials would aid in applicants getting approval for demolishing historic buildings and homes. Sam Breidenbach, also a member of MTHP, further cited concerns over process to approve changes moving too quickly, highlighting the importance of the approval process and how it should not be rushed. Breidenbach further stated concern over the language used in Standard 6.i, which goes over unsalvageable buildings. This is again a callback to previous applications, notably the Vilas homes, where there were no city building inspectors or neutral party contractors involved in determining the livable conditions of the homes.

MTHP overall argued for changing the language in the new orendance to include “sufficiently” in proving building conditions. Commissioner Heck later asked about the City taking this into consideration, to which Tuttle differed to City attorneys for input on wording. It was ultimately determined to be unnecessary due to the nature of the orendance, with "sufficiently” already being implied by the legal language used.


#### Accessory Dwelling Units and Encroachments
Reaching their final item of the night, the Commission evaluated an amendment to a Chapter 28 section related to accessory dwelling units (ADUs) and infills. Katie Bannon, the City’s Zoning Administrator, went over a request their office received in evaluating how the City can make single family homes easier to build and improve, as well as identify current obstacles in obtaining middle housing. Zoning found the main obstacles to be encroachment limits and usable space requirements.

Bannon highlighted a number of situations which the current restraints would not allow for additions, such as side porches on multi-family homes, limits to garage placement/sizing, and ADU design constraints. Currently, the city has strict requirements for the width of garage doors on street facing facades, which was put into place in 2013. Bannon noted there are a number of homes in Madison that were built prior to 2013 which do not comply, but follow the overall intent of the regulations. This can often cause confusion and lost money with new builds, as developers are not always aware of the constraints—meaning homeowners obtain blueprints, materials, and build contracts before realizing their design is technically against Madison’s ordinances.

Bannon then went over the addition of two new approved modular designs for ADUs, which will double the number of unit styles allowed by the City. As part of their evaluation, Zoning identified corner lots as struggling the most to add ADUs due to encroachment limits and size constraints set by usable space requirements. Currently, single family homes ar required to maintain 200 square feet of usable private space, which cannot include front yards, driveways, alleyways, or paved side paths. Zoning was able to determine allowing for more flexibility in usable space would not have a negative impact on residents, but could ultimately help address the city’s housing crisis by creating the oppotunity to provide more livable space in central areas.

This was met with mixed views from the pubic. Grant Foster, a Madison local, supported the changes, stating fillable units would also be supported by access to public transportation whereas building on the outskirts of the city limits access to the bus lines. Foster furthered their support by requesting the height limit for ADUs be increased by three feet to allow ADU residents more room to move around, as well as requested the ability to add a second ADU to properties with considerable space. Overall, Foster seems to support rent culture, claiming the return on ADU rentals would create a higher return for homeowners than the overall cost of adding the units themselves. While some may not be in favor of more rental units, they do in fact have the ability to create more housing to help meet current need.

This is in contrast to Madison resident Linda Leonard’s stance that usable space requirements need to be maintained. Leonard’s biggest concern: children not having space at their own home and having to walk to local parks in order to spend time outside. Leonard also voiced the possibility of Madison creating “warehouse housing,” with smaller units stacked up all over Madison, rather than helping to address missing middle housing.

Commissioner Heck asked for more information from Bannon on the impact in increasing height limits for ADUs, to which Bannon replied the height was outside of their investigative scope, but she had no objections so long as the units did not match or exceed the existing single family structures. The Plan Commission decided to ask for an amendment to their height to allow for an increase before going over issues for upcoming meetings and adjourning for the night. At their next meeting, residents can expect the conditional use for a drive through window on Lien Road to be discussed, as well as updates to FEMA’s flood plain requirements and how the city will have to address changes in order to remain eligible for flood insurance.

